use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'YZBaseUI_Example' do
  pod 'YZBaseUI', :path => '../'

  target 'YZBaseUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
